### ISSUE TITLE
Clone the git repository to my computer

### ISSUE THREAD

**Issue by TheodorosPapanikolaou** [Asterics2020-Obelics/School2019#3]
Hello,

I am Theodoros Papanikolaou from APC, Paris.

When I am trying to clone the git repository on my personal computer by writing on the terminal the following command

git clone https://github.com/Asterics2020-Obelics/School2019.git

I receive the following message:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

I have a macOS Mojave, Version 10.14.3

Do you know how can I fix this issue?

Theodoros

**Comment by maxnoe** [comment]
Hi,

Try updating the xcode-tools using:

```
$ xcode-select --install
```

**Comment by TheodorosPapanikolaou** [comment]
Nice! Thank you very much! 

Done! 

Theodoros
