### ISSUE TITLE
Python Settings

### ISSUE THREAD

**Issue by TheodorosPapanikolaou** [Asterics2020-Obelics/School2019#5]
Hello to the group!

I am Theodoros Papanikolaou, from APC Paris.

I had already installed Python 2.7 on my Mac but now I downloaded and installed also Python 3.7 as recommended in the instructions.

When I go to the directory in which I have installed anaconda3 and write in the terminal 

bash Anaconda3-2018.12-MacOSX-x86_64.sh -b -p $HOME/.local/anaconda3

I take the following error message:
 
bash: Anaconda3-2018.12-MacOSX-x86_64.sh: No such file or directory.

Should have I written this command in another directory or should I find somewhere else this file?

Theodoros

**Comment by vuillaut** [comment]
See point 2. of instructions:
[Download](https://www.anaconda.com/distribution/#download-section) the Linux `Anaconda` installer for Python 3.7.

**Comment by maxnoe** [comment]
> Should have I written this command in another directory or should I find somewhere else this file?

The file is the one you download from anaconda, so you need to runs this in your `Downloads` folder or whereever you saved the downloaded file.

I will clarify this part.

**Comment by TheodorosPapanikolaou** [comment]
Nice! Thanks for the clarification! 

Theodoros
