### ISSUE TITLE
Library Requirements

### ISSUE THREAD

**Issue by TheodorosPapanikolaou** [Asterics2020-Obelics/School2019#8]
Hi again!

When I write  in the directory in which I cloned  the School2019 repository the following command

conda env create -f environment.yml

I take the following message

Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound: 
  - gcc-7

Do you know how I can proceed?

Theodoros

PS: Previously, I did not find the file .bash_profile in the directory /.local/anaconda3. So, I created this file with the command "touch .bash_profile", I opened it with the command "open -e .bash_profile" and I wrote inside the two lines mentioned in the instructions.

. "$HOME/.local/anaconda3/etc/profile.d/conda.sh"
conda activate

Then, I moved to the Library Requirements in which I have the issue described above. Did I follow the correct procedure for the .bash_profile?

**Comment by maxnoe** [comment]
Hi, we just updated the needed packages and the installation instructions. (and we might do it again before the workshop starts).

To get the changes, run `git pull` in the repository, and try again running

```
conda env create -f environment.yml
conda activate school19
```

And the other commands to install clang that are now added to the readme

**Comment by TheodorosPapanikolaou** [comment]
Nice!

Thank you very much! Solved!

Theodoros
